Output Explanation for `create_cert_request.sh` Script

    The output generated by running the `create_cert_request.sh` script is as follows:

    $ ./create_cert_request.sh
    Creating certificate request...
    Certificate request created and saved to cert_request.csr

    Detailed Explanation

    1. Running the `create_cert_request.sh` Script

    To execute the `create_cert_request.sh` script, use the following command in your terminal:

    $ ./create_cert_request.sh

    $: This symbol represents the command prompt in the terminal.

    ./: This specifies the current directory. It tells the shell to look for the script in the current directory.

    create_cert_request.sh: This is the name of the script file you want to execute.

    2. Initial Message:

    Creating certificate request...

    This line is printed by the script when it starts running. It informs the user that the script is in the process of creating a certificate request. This provides feedback to the user, indicating that the script is 
    executing as intended.

    3. Request Creation Confirmation:

    Certificate request created and saved to `cert_request.csr`

    This line indicates that the script has completed the process of creating the certificate request. It confirms that the certificate request has been created and saved to a file named `cert_request.csr`. This message 
    assures the user that the task has been successfully completed.

    Professional Summary
    The above output demonstrates the successful execution of the `create_cert_request.sh` script. The script provides clear and concise feedback to the user, indicating both the start and the completion of the certificate 
    request creation process.

    For a detailed description of the creation process of create_cert_request.sh, please refer to : Creation Process of create_cert_request.sh Script
