Explanation of Output for `create_cert_request.sh` Script

The output below demonstrates the expected result from executing create_cert_request.sh:

create_cert_request.sh
Creating certificate request...
Certificate request created and saved to cert_request.csr

Breakdown of Output:

`create_cert_request.sh`: Indicates the name of the script executed.

Creating certificate request...: Output generated by the script indicating the process of creating a certificate request.

Certificate request created and saved to cert_request.csr: Confirmation that the script successfully created and saved the certificate request to `cert_request.csr`.

 Understanding these details enhances transparency and usability in managing certificate requests.

