Output Explanation for `sign_cert_request.sh` Script

    The output generated by running the `sign_cert_request.sh` script is as follows:

    $ ./sign_cert_request.sh
    Simulating signing of CSR...
    CSR signed and saved to signed_cert.crt

    Detailed Explanation

    1. **Running the `sign_cert_request.sh` Script:

    To execute the `sign_cert_request.sh` script, use the following command in your terminal:

    $ ./sign_cert_request.sh

   `$`: This symbol represents the command prompt in the terminal.

    `./`: Specifies the current directory. It tells the shell to look for the script in the current directory.

    `sign_cert_request.sh`: This is the name of the script file you want to execute.

    2. Initial Message

    Simulating signing of CSR...

    This line is printed by the script when it starts running. It informs the user that the script is beginning the process of simulating the signing of a Certificate Signing Request (CSR). This initial message is helpful 
    for providing feedback to the user that the script is executing as expected.

    3. Signing Confirmation

    CSR signed and saved to signed_cert.crt

    This line confirms that the script has completed the simulation process. It indicates that the CSR has been successfully signed and saved to a file named `signed_cert.crt`.

    Professional Summary
    The above output demonstrates the successful execution of the `sign_cert_request.sh` script. The script provides clear and concise feedback to the user, indicating the start and completion of the CSR signing simulation 
    process.

    For a detailed description of the creation process of sign_cert_request.sh, please refer to : Creation Process of sign_cert_request.sh Script
